server:
  port: 8080



mybatis:
  type-aliases-package: com.itszt.domain
  mapper-locations: classpath*:com/itszt/mapper/**/*.xml


spring:
  datasource:
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.186.253:8801/db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 5
      max-idle: 200
  jackson:
    date-format: YYYY-MM-DD hh:mm:ss
  rabbitmq:
    host: 182.92.90.73
    port: 5673
    username: admin
    password: admin
    publisher-confirm: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
logging:
  level:
    root: info
  config: classpath:logback.xml
