server:
  port: 8080



mybatis:
  type-aliases-package: com.itszt.domain
  mapper-locations: classpath*:com/itszt/mapper/**/*.xml


spring:
  datasource:
    username: dt
    password: dt
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.200.115:3306/dt?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 5
      max-idle: 200
  jackson:
    date-format: YYYY-MM-DD hh:mm:ss
#  rabbitmq:
#    host: 182.92.90.73
#    port: 5673
#    username: admin
#    password: admin
#    publisher-confirm: true
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual
  task:
    execution:
      pool:
        core-size: 10

logging:
  level:
    root: info
  config: classpath:logback.xml
ali:
  mail:
    protocol: smtp
    host: smtp.knowlegene.com
    port: 25
    address: product-service@knowlegene.com
    password: zYzh123456
    isauth: true
    isenableddebugmod: true

